apiVersion: v1
kind: Service
metadata:
  name: cart-microservice
  labels:
    app: gateway
    service: cart-microservice
spec:
  selector:
    app: cart
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-microservice-v1
  labels:
    app: cart
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
      version: v1
  template:
    metadata:
      labels:
        app: cart
        version: v1
    spec:
      containers:
      - name: cart
        image: nchandrappa/cart-microservice-v1:latest
        envFrom:
        - configMapRef:
            name: cart-microservice-v1-properties
        ports:
        - containerPort: 8080