apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-microservice
  labels:
    app: checkout
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkout
      version: v1
  template:
    metadata:
      labels:
        app: checkout
        version: v1
    spec:
      containers:
      - name: checkout
        image: nchandrappa/checkout-microservice:latest
        envFrom:
        - configMapRef:
            name: checkout-microservice-properties
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: checkout-microservice
spec:
  selector:
    app: checkout
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
