apiVersion: apps/v1
kind: Deployment
metadata:
  name: sappho-retailapp-ui
  labels:
    app: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: sappho-retailapp-ui
        image: nchandrappa/sappho-retailapp-ui
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sappho-retailapp-ui-lb
spec:
  type: LoadBalancer
  selector:
    app: ui
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
