apiVersion: apps/v1
kind: Deployment
metadata:
  name: sappho-retailapp-ui
  labels:
    app: ui
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
      version: v1
  template:
    metadata:
      labels:
        app: ui
        version: v1
    spec:
      containers:
      - name: sappho-retailapp-ui
        image: nchandrappa/sappho-retailapp-ui
        envFrom:
        - configMapRef:
            name: yugastore-ui-properties
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: yugastore-ui
spec:
  selector:
    app: ui
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
